name: HTML Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        run: git checkout gh-page
      - name: clone
        run: git clone --depth 1 git@github.com:Vincent550102/NCKU-Classboard-Simulator.git