name: HTML Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        run: git checkout gh-page
      - name: clone
        run: git clone --depth 1 https://github.com/Vincent550102/NCKU-Classboard-Simulator.git
      - name: commit gh-page
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "bot commit"
          git push